; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font, s16 Bold, Calibri
Gui Add, Button, gAwnser x12 y2 w143 h60, &Answer
Gui Font

Gui Show, w167 h72, IPC
Return

Awnser:
        IfWinExist ahk_class CIPCOMMUNICATOR
     {
          WinActivate ahk_class CIPCOMMUNICATOR
          Send {F2}
     }
Return

LAlt & a::

     IfWinExist ahk_class CIPCOMMUNICATOR

     {

          WinActivate ahk_class CIPCOMMUNICATOR

          Send {F2}

     }

return

LAlt & s::

     IfWinExist ahk_class CIPCOMMUNICATOR

     {

          WinActivate ahk_class CIPCOMMUNICATOR

          Send {F3}

     }

return

LAlt & d::

     IfWinExist ahk_class CIPCOMMUNICATOR

     {

          WinActivate ahk_class CIPCOMMUNICATOR

          Send {F4}

     }

return

LAlt & z::

     IfWinExist ahk_class CIPCOMMUNICATOR

     {

          WinActivate ahk_class CIPCOMMUNICATOR

          Send {F5}

     }

return

LAlt & x::

     IfWinExist ahk_class CIPCOMMUNICATOR

     {

          WinActivate ahk_class CIPCOMMUNICATOR

          Send {F5}

     }

return


GuiEscape:
GuiClose:
    ExitApp
